name: Publish Snapshot

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew build publishToMavenLocal

      - name: Sign artifacts
        run: |
          gpg --batch --yes --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" --import <(echo "$GPG_PRIVATE_KEY")
          for file in build/libs/*.jar build/libs/*-sources.jar build/libs/*-javadoc.jar build/publications/mavenJava/pom-default.xml; do
            gpg --batch --yes --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" -ab "$file"
          done
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Configure Maven settings.xml
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: '[{"id": "ossrh", "username": "${{ secrets.OSSRH_USERNAME }}", "password": "${{ secrets.OSSRH_TOKEN }}"}]'

      - name: Deploy to Sonatype SNAPSHOT
        run: |
          VERSION=$(./gradlew -q properties | grep "^version:" | awk '{ print $2 }')
          mvn deploy:deploy-file \
            -DpomFile=build/publications/mavenJava/pom-default.xml \
            -Dfile=build/libs/equation-parser-${VERSION}.jar \
            -Dsources=build/libs/equation-parser-${VERSION}-sources.jar \
            -Djavadoc=build/libs/equation-parser-${VERSION}-javadoc.jar \
            -Dfiles=build/libs/equation-parser-${VERSION}.jar.asc,build/libs/equation-parser-${VERSION}-sources.jar.asc,build/libs/equation-parser-${VERSION}-javadoc.jar.asc,build/publications/mavenJava/pom-default.xml.asc \
            -Dclassifiers=jar.asc,sources.asc,javadoc.asc,pom.asc \
            -Dtypes=asc,asc,asc,asc \
            -DrepositoryId=ossrh \
            -Durl=https://central.sonatype.com/repository/maven-snapshots \
            -DgroupId=io.github.lordtylus.equation \
            -DartifactId=equation-parser \
            -Dversion=${VERSION}
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
